export const AUTH_TOKEN_KEY = "c5e95ff7-2624-495b-937d-027c09474f85";
export const THEME_KEY = "VIBE-ADMIN-PANEL-THEME";
export const API_BASE_URL = "http://localhost:8000/api/v1";
export const FILE_BASE_URL = "http://localhost:8000/static/";

type Genre = { imageUrl: string; title: string };

// const genresArr = [
//   "Pop",
//   "Rock",
//   "Hip Hop",
//   "Rap",
//   "R&B",
//   "Soul",
//   "Jazz",
//   "Blues",
//   "Country",
//   "Classical",
//   "Electronic",
//   "Dance",
//   "House",
//   "Trance",
//   "Techno",
//   "Dubstep",
//   "Reggae",
//   "Reggaeton",
//   "Latin",
//   "Afrobeat",
//   "Indie",
//   "Alternative",
//   "Folk",
//   "Metal",
//   "Punk",
//   "Funk",
//   "Disco",
//   "Lo-fi",
//   "Chillhop",
//   "Soundtrack",
//   "K-Pop",
//   "J-Pop",
//   "EDM",
//   "Gospel",
//   "Opera",
//   "Trap",
//   "Drill",
//   "Ambient",
//   "Grime",
//   "Ska",
//   "Synthwave",
//   "Industrial",
//   "Experimental",
//   "Acoustic",
//   "Instrumental",
// ] as const;

export const genresArr: Genre[] = [
  { title: "Pop", imageUrl: "/icons/music-pop-icon.svg" },
  { title: "Rock", imageUrl: "/icons/music-rock-icon.svg" },
  { title: "Rap", imageUrl: "/icons/music-rap-icon.svg" },
  { title: "Hip Hop", imageUrl: "/icons/music-hiphop-icon.svg" },
  { title: "R&B", imageUrl: "/icons/music-r&b-icon.svg" },
  { title: "Soul", imageUrl: "/icons/music-soul-icon.svg" },
  { title: "Jazz", imageUrl: "/icons/music-jazz-icon.svg" },
  { title: "Blues", imageUrl: "/icons/music-blues-icon.svg" },
  { title: "Country", imageUrl: "/icons/music-country-icon.svg" },
  { title: "Classical", imageUrl: "/icons/music-classical-icon.svg" },
  { title: "Dance", imageUrl: "/icons/music-dance-icon.svg" },
  { title: "Electronic", imageUrl: "/icons/music-electronic-icon.svg" },
  { title: "House", imageUrl: "/icons/music-house-icon.svg" },
  { title: "Dubstep", imageUrl: "/icons/music-dubset-icon.svg" },
  { title: "Techno", imageUrl: "/icons/music-techno-icon.svg" },
  { title: "Trance", imageUrl: "/icons/music-trance-icon.svg" },
  { title: "Reggae", imageUrl: "/icons/music-reggae-icon.svg" },
  { title: "Reggaeton", imageUrl: "/icons/music-reggaeton-icon.svg" },
  { title: "Latin", imageUrl: "/icons/music-latin-icon.svg" },
  { title: "Afrobeat", imageUrl: "/icons/music-afrobeat-icon.svg" },
  { title: "Indie", imageUrl: "/icons/music-Indie-icon.svg" },
  { title: "Alternative", imageUrl: "/icons/music-alternative-icon.svg" },
  { title: "Ambient", imageUrl: "/icons/music-ambient-icon.svg" },
  { title: "Chilling", imageUrl: "/icons/music-chillhop-icon.svg" },
  { title: "Disco", imageUrl: "/icons/music-disco-icon.svg" },
  { title: "Drill", imageUrl: "/icons/music-drill-icon.svg" },
  { title: "EDM", imageUrl: "/icons/music-edm-icon.svg" },
  { title: "Folk", imageUrl: "/icons/music-folk-icon.svg" },
  { title: "Funk", imageUrl: "/icons/music-funk-icon.svg" },
  { title: "Gospel", imageUrl: "/icons/music-gospel-icon.svg" },
  { title: "Grime", imageUrl: "/icons/music-grime-icon.svg" },
  { title: "K-Pop", imageUrl: "/icons/music-k-pop-icon.svg" },
  { title: "Lo-Fi", imageUrl: "/icons/music-lo-fi-icon.svg" },
  { title: "Metal", imageUrl: "/icons/music-metal-icon.svg" },
  { title: "Opera", imageUrl: "/icons/music-opera-icon.svg" },
  { title: "Punk", imageUrl: "/icons/music-punk-icon.svg" },
  { title: "Soundtrack", imageUrl: "/icons/music-soundtrack-icon.svg" },
  { title: "Trap", imageUrl: "/icons/music-trap-icon.svg" },
];
export const categoriesArr: CategoryObject[] = [
  { title: "Chill", bgColorCode: "#D4EFFB", textColorCode: "#000000" },
  { title: "Energetic", bgColorCode: "#FFB67A", textColorCode: "#000000" },
  { title: "Workout", bgColorCode: "#FF8A66", textColorCode: "#000000" },
  { title: "Party", bgColorCode: "#D75C66", textColorCode: "#FFFFFF" },
  { title: "Study", bgColorCode: "#A29BFE", textColorCode: "#FFFFFF" },
  { title: "Sleep", bgColorCode: "#A9D4FB", textColorCode: "#000000" },
  { title: "Romantic", bgColorCode: "#FF9DA9", textColorCode: "#000000" },
  { title: "Sad", bgColorCode: "#B0BEC9", textColorCode: "#000000" },
  { title: "Happy", bgColorCode: "#FAE588", textColorCode: "#000000" },
  { title: "Uplifting", bgColorCode: "#7BE1DE", textColorCode: "#000000" },
  { title: "Dark", bgColorCode: "#4B5253", textColorCode: "#FFFFFF" },
  { title: "Melancholic", bgColorCode: "#9BA2A5", textColorCode: "#000000" },
  { title: "Relaxing", bgColorCode: "#B2F1F1", textColorCode: "#000000" },
  { title: "Hype", bgColorCode: "#F98DBA", textColorCode: "#000000" },
  { title: "Epic", bgColorCode: "#96456E", textColorCode: "#FFFFFF" },
  { title: "Cinematic", bgColorCode: "#5E4B9C", textColorCode: "#FFFFFF" },
  { title: "Morning", bgColorCode: "#FFF2CD", textColorCode: "#000000" },
  { title: "Night", bgColorCode: "#3C348C", textColorCode: "#FFFFFF" },
  { title: "Rainy Day", bgColorCode: "#A9D4FB", textColorCode: "#000000" },
  { title: "Road Trip", bgColorCode: "#FFD4C7", textColorCode: "#000000" },
  { title: "Driving", bgColorCode: "#A9F7E4", textColorCode: "#000000" },
  { title: "Throwback", bgColorCode: "#C4BDFF", textColorCode: "#000000" },
  { title: "80s", bgColorCode: "#FABEEE", textColorCode: "#000000" },
  { title: "90s", bgColorCode: "#FFD2F6", textColorCode: "#000000" },
  { title: "2000s", bgColorCode: "#FEE8B2", textColorCode: "#000000" },
  { title: "2010s", bgColorCode: "#A5F2F2", textColorCode: "#000000" },
  { title: "2020s", bgColorCode: "#92EDD2", textColorCode: "#000000" },
  { title: "Viral", bgColorCode: "#F66A5A", textColorCode: "#FFFFFF" },
  { title: "Trending", bgColorCode: "#73C6F1", textColorCode: "#000000" },
  { title: "New Release", bgColorCode: "#80E8C3", textColorCode: "#000000" },
  { title: "Classic", bgColorCode: "#8A99A5", textColorCode: "#000000" },
  { title: "Acoustic", bgColorCode: "#FFF0B8", textColorCode: "#000000" },
  { title: "Instrumental", bgColorCode: "#B5F6CE", textColorCode: "#000000" },
  { title: "Cover", bgColorCode: "#FFE07A", textColorCode: "#000000" },
  { title: "Remix", bgColorCode: "#FFA589", textColorCode: "#000000" },
  { title: "Mashup", bgColorCode: "#FFA9A9", textColorCode: "#000000" },
  { title: "Live", bgColorCode: "#4869B3", textColorCode: "#FFFFFF" },
  { title: "Danceable", bgColorCode: "#FCE0CB", textColorCode: "#000000" },
  { title: "Background", bgColorCode: "#F1FCFD", textColorCode: "#000000" },
  { title: "Motivational", bgColorCode: "#FFF3B2", textColorCode: "#000000" },
  { title: "Emotional", bgColorCode: "#D96DAD", textColorCode: "#000000" },
  { title: "Heartbreak", bgColorCode: "#D8E2B3", textColorCode: "#000000" },
  { title: "Love", bgColorCode: "#FABEEE", textColorCode: "#000000" },
  { title: "Breakup", bgColorCode: "#E5F6A3", textColorCode: "#000000" },
  { title: "Summer", bgColorCode: "#FFD18C", textColorCode: "#000000" },
  { title: "Winter", bgColorCode: "#E4ECF3", textColorCode: "#000000" },
  { title: "Spring", bgColorCode: "#A9F7E4", textColorCode: "#000000" },
  { title: "Autumn", bgColorCode: "#FFAD7D", textColorCode: "#000000" },
  { title: "Gaming", bgColorCode: "#A5A0DD", textColorCode: "#FFFFFF" },
  { title: "Focus", bgColorCode: "#92EDD2", textColorCode: "#000000" },
  { title: "Meditation", bgColorCode: "#66D6BA", textColorCode: "#000000" },
];
