export const AUTH_TOKEN_KEY = "c5e95ff7-2624-495b-937d-027c09474f85";
export const THEME_KEY = "VIBE-ADMIN-PANEL-THEME";
export const API_BASE_URL = "http://localhost:8000/api/v1";
export const FILE_BASE_URL = "http://localhost:8000/static/";

type Genre = { imageUrl: string; title: string };

// const genresArr = [
//   "Pop",
//   "Rock",
//   "Hip Hop",
//   "Rap",
//   "R&B",
//   "Soul",
//   "Jazz",
//   "Blues",
//   "Country",
//   "Classical",
//   "Electronic",
//   "Dance",
//   "House",
//   "Trance",
//   "Techno",
//   "Dubstep",
//   "Reggae",
//   "Reggaeton",
//   "Latin",
//   "Afrobeat",
//   "Indie",
//   "Alternative",
//   "Folk",
//   "Metal",
//   "Punk",
//   "Funk",
//   "Disco",
//   "Lo-fi",
//   "Chillhop",
//   "Soundtrack",
//   "K-Pop",
//   "J-Pop",
//   "EDM",
//   "Gospel",
//   "Opera",
//   "Trap",
//   "Drill",
//   "Ambient",
//   "Grime",
//   "Ska",
//   "Synthwave",
//   "Industrial",
//   "Experimental",
//   "Acoustic",
//   "Instrumental",
// ] as const;

export const genresArr: Genre[] = [
  { title: "Pop", imageUrl: "/icons/music-pop-icon.svg" },
  { title: "Rock", imageUrl: "/icons/music-rock-icon.svg" },
  { title: "Rap", imageUrl: "/icons/music-rap-icon.svg" },
  { title: "HipHop", imageUrl: "/icons/music-hiphop-icon.svg" },
  { title: "R&B", imageUrl: "/icons/music-r&b-icon.svg" },
];

export const categoriesArr = [
  { title: "Chill", colorCode: "#AEDFF7" },
  { title: "Energetic", colorCode: "#FF8C42" },
  { title: "Workout", colorCode: "#FF5733" },
  { title: "Party", colorCode: "#C70039" },
  { title: "Study", colorCode: "#6C5CE7" },
  { title: "Sleep", colorCode: "#74B9FF" },
  { title: "Romantic", colorCode: "#FF6B81" },
  { title: "Sad", colorCode: "#8395A7" },
  { title: "Happy", colorCode: "#F9CA24" },
  { title: "Uplifting", colorCode: "#00CEC9" },
  { title: "Dark", colorCode: "#2D3436" },
  { title: "Melancholic", colorCode: "#636E72" },
  { title: "Relaxing", colorCode: "#81ECEC" },
  { title: "Hype", colorCode: "#E84393" },
  { title: "Epic", colorCode: "#6D214F" },
  { title: "Cinematic", colorCode: "#341F97" },
  { title: "Morning", colorCode: "#FFEAA7" },
  { title: "Night", colorCode: "#1B1464" },
  { title: "Rainy Day", colorCode: "#74B9FF" },
  { title: "Road Trip", colorCode: "#FAB1A0" },
  { title: "Driving", colorCode: "#55EFC4" },
  { title: "Throwback", colorCode: "#A29BFE" },
  { title: "80s", colorCode: "#F368E0" },
  { title: "90s", colorCode: "#FF9FF3" },
  { title: "2000s", colorCode: "#FDCB6E" },
  { title: "2010s", colorCode: "#00D2D3" },
  { title: "2020s", colorCode: "#1DD1A1" },
  { title: "Viral", colorCode: "#E84118" },
  { title: "Trending", colorCode: "#0097E6" },
  { title: "New Release", colorCode: "#10AC84" },
  { title: "Classic", colorCode: "#576574" },
  { title: "Acoustic", colorCode: "#ECCC68" },
  { title: "Instrumental", colorCode: "#7BED9F" },
  { title: "Cover", colorCode: "#FFA502" },
  { title: "Remix", colorCode: "#FF6348" },
  { title: "Mashup", colorCode: "#FF6B6B" },
  { title: "Live", colorCode: "#1E3799" },
  { title: "Danceable", colorCode: "#F8C291" },
  { title: "Background", colorCode: "#DFF9FB" },
  { title: "Motivational", colorCode: "#F6E58D" },
  { title: "Emotional", colorCode: "#B53471" },
  { title: "Heartbreak", colorCode: "#BDC581" },
  { title: "Love", colorCode: "#F368E0" },
  { title: "Breakup", colorCode: "#C4E538" },
  { title: "Summer", colorCode: "#FFB142" },
  { title: "Winter", colorCode: "#C8D6E5" },
  { title: "Spring", colorCode: "#55EFC4" },
  { title: "Autumn", colorCode: "#FF793F" },
  { title: "Gaming", colorCode: "#706FD3" },
  { title: "Focus", colorCode: "#1DD1A1" },
  { title: "Meditation", colorCode: "#00B894" },
];
