export const AUTH_TOKEN_KEY = "c5e95ff7-2624-495b-937d-027c09474f85";
export const THEME_KEY = "VIBE-ADMIN-PANEL-THEME";
export const API_BASE_URL = "http://localhost:8000/api/v1";
export const FILE_BASE_URL = "http://localhost:8000/static/";

type Genre = { imageUrl: string; title: string };

// const genresArr = [
//   "Pop",
//   "Rock",
//   "Hip Hop",
//   "Rap",
//   "R&B",
//   "Soul",
//   "Jazz",
//   "Blues",
//   "Country",
//   "Classical",
//   "Electronic",
//   "Dance",
//   "House",
//   "Trance",
//   "Techno",
//   "Dubstep",
//   "Reggae",
//   "Reggaeton",
//   "Latin",
//   "Afrobeat",
//   "Indie",
//   "Alternative",
//   "Folk",
//   "Metal",
//   "Punk",
//   "Funk",
//   "Disco",
//   "Lo-fi",
//   "Chillhop",
//   "Soundtrack",
//   "K-Pop",
//   "J-Pop",
//   "EDM",
//   "Gospel",
//   "Opera",
//   "Trap",
//   "Drill",
//   "Ambient",
//   "Grime",
//   "Ska",
//   "Synthwave",
//   "Industrial",
//   "Experimental",
//   "Acoustic",
//   "Instrumental",
// ] as const;

export const genresArr: Genre[] = [
  { title: "Pop", imageUrl: "/icons/music-pop-icon.svg" },
  { title: "Rock", imageUrl: "/icons/music-rock-icon.svg" },
  { title: "Rap", imageUrl: "/icons/music-rap-icon.svg" },
  { title: "Hip Hop", imageUrl: "/icons/music-hiphop-icon.svg" },
  { title: "R&B", imageUrl: "/icons/music-r&b-icon.svg" },
  { title: "Soul", imageUrl: "/icons/music-soul-icon.svg" },
  { title: "Jazz", imageUrl: "/icons/music-jazz-icon.svg" },
  { title: "Blues", imageUrl: "/icons/music-blues-icon.svg" },
  { title: "Country", imageUrl: "/icons/music-country-icon.svg" },
  { title: "Classical", imageUrl: "/icons/music-classical-icon.svg" },
  { title: "Dance", imageUrl: "/icons/music-dance-icon.svg" },
  { title: "Electronic", imageUrl: "/icons/music-electronic-icon.svg" },
  { title: "House", imageUrl: "/icons/music-house-icon.svg" },
  { title: "Dubstep", imageUrl: "/icons/music-dubstep-icon.svg" },
  { title: "Techno", imageUrl: "/icons/music-techno-icon.svg" },
  { title: "Trance", imageUrl: "/icons/music-trance-icon.svg" },
  { title: "Reggae", imageUrl: "/icons/music-reggae-icon.svg" },
  { title: "Reggaeton", imageUrl: "/icons/music-reggaeton-icon.svg" },
  { title: "Latin", imageUrl: "/icons/music-latin-icon.svg" },
  { title: "Afrobeat", imageUrl: "/icons/music-afrobeat-icon.svg" },
  { title: "Indie", imageUrl: "/icons/music-indie-icon.svg" },
];
export const categoriesArr: {
  title: string;
  bgColorCode: string;
  textColorCode: string;
}[] = [
  { title: "Chill", bgColorCode: "#AEDFF7", textColorCode: "#000000" },
  { title: "Energetic", bgColorCode: "#FF8C42", textColorCode: "#000000" },
  { title: "Workout", bgColorCode: "#FF5733", textColorCode: "#FFFFFF" },
  { title: "Party", bgColorCode: "#C70039", textColorCode: "#FFFFFF" },
  { title: "Study", bgColorCode: "#6C5CE7", textColorCode: "#FFFFFF" },
  { title: "Sleep", bgColorCode: "#74B9FF", textColorCode: "#000000" },
  { title: "Romantic", bgColorCode: "#FF6B81", textColorCode: "#000000" },
  { title: "Sad", bgColorCode: "#8395A7", textColorCode: "#FFFFFF" },
  { title: "Happy", bgColorCode: "#F9CA24", textColorCode: "#000000" },
  { title: "Uplifting", bgColorCode: "#00CEC9", textColorCode: "#000000" },
  { title: "Dark", bgColorCode: "#2D3436", textColorCode: "#FFFFFF" },
  { title: "Melancholic", bgColorCode: "#636E72", textColorCode: "#FFFFFF" },
  { title: "Relaxing", bgColorCode: "#81ECEC", textColorCode: "#000000" },
  { title: "Hype", bgColorCode: "#E84393", textColorCode: "#FFFFFF" },
  { title: "Epic", bgColorCode: "#6D214F", textColorCode: "#FFFFFF" },
  { title: "Cinematic", bgColorCode: "#341F97", textColorCode: "#FFFFFF" },
  { title: "Morning", bgColorCode: "#FFEAA7", textColorCode: "#000000" },
  { title: "Night", bgColorCode: "#1B1464", textColorCode: "#FFFFFF" },
  { title: "Rainy Day", bgColorCode: "#74B9FF", textColorCode: "#000000" },
  { title: "Road Trip", bgColorCode: "#FAB1A0", textColorCode: "#000000" },
  { title: "Driving", bgColorCode: "#55EFC4", textColorCode: "#000000" },
  { title: "Throwback", bgColorCode: "#A29BFE", textColorCode: "#000000" },
  { title: "80s", bgColorCode: "#F368E0", textColorCode: "#000000" },
  { title: "90s", bgColorCode: "#FF9FF3", textColorCode: "#000000" },
  { title: "2000s", bgColorCode: "#FDCB6E", textColorCode: "#000000" },
  { title: "2010s", bgColorCode: "#00D2D3", textColorCode: "#000000" },
  { title: "2020s", bgColorCode: "#1DD1A1", textColorCode: "#000000" },
  { title: "Viral", bgColorCode: "#E84118", textColorCode: "#FFFFFF" },
  { title: "Trending", bgColorCode: "#0097E6", textColorCode: "#FFFFFF" },
  { title: "New Release", bgColorCode: "#10AC84", textColorCode: "#FFFFFF" },
  { title: "Classic", bgColorCode: "#576574", textColorCode: "#FFFFFF" },
  { title: "Acoustic", bgColorCode: "#ECCC68", textColorCode: "#000000" },
  { title: "Instrumental", bgColorCode: "#7BED9F", textColorCode: "#000000" },
  { title: "Cover", bgColorCode: "#FFA502", textColorCode: "#000000" },
  { title: "Remix", bgColorCode: "#FF6348", textColorCode: "#000000" },
  { title: "Mashup", bgColorCode: "#FF6B6B", textColorCode: "#000000" },
  { title: "Live", bgColorCode: "#1E3799", textColorCode: "#FFFFFF" },
  { title: "Danceable", bgColorCode: "#F8C291", textColorCode: "#000000" },
  { title: "Background", bgColorCode: "#DFF9FB", textColorCode: "#000000" },
  { title: "Motivational", bgColorCode: "#F6E58D", textColorCode: "#000000" },
  { title: "Emotional", bgColorCode: "#B53471", textColorCode: "#FFFFFF" },
  { title: "Heartbreak", bgColorCode: "#BDC581", textColorCode: "#000000" },
  { title: "Love", bgColorCode: "#F368E0", textColorCode: "#000000" },
  { title: "Breakup", bgColorCode: "#C4E538", textColorCode: "#000000" },
  { title: "Summer", bgColorCode: "#FFB142", textColorCode: "#000000" },
  { title: "Winter", bgColorCode: "#C8D6E5", textColorCode: "#000000" },
  { title: "Spring", bgColorCode: "#55EFC4", textColorCode: "#000000" },
  { title: "Autumn", bgColorCode: "#FF793F", textColorCode: "#000000" },
  { title: "Gaming", bgColorCode: "#706FD3", textColorCode: "#FFFFFF" },
  { title: "Focus", bgColorCode: "#1DD1A1", textColorCode: "#000000" },
  { title: "Meditation", bgColorCode: "#00B894", textColorCode: "#FFFFFF" },
];
